  # MariaDB - MySQL Database
version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  backend:
  default:
    driver: bridge

########################### Volumes
volumes:
  db_data:
  nextcloud:
  nextcloud_config:
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/iscsi/nextcloud_data
  nextcloud_apps:
########################### SERVICES
services:
  
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    networks:
    - backend
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - POSTGRES_ROOT_PASSWORD=$POSTGRES_ROOT_PASSWORD
      - POSTGRES_PASSWORD=$NEXTCLOUD_POSTGRES_PASSWORD
      - POSTGRES_DB=$NEXTCLOUD_POSTGRES_DATABASE
      - POSTGRES_USER=$NEXTCLOUD_POSTGRES_USER  
  
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
    - backend

  nextcloud:
    container_name: nextcloud
    hostname: nextcloud
    image: nextcloud:fpm-alpine
    restart: always
    networks:
      - t2_proxy
      - backend
    links: 
      - db
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: nextcloud_apps
        target: /var/www/html/custom_apps
      - type: volume
        source: nextcloud_config
        target: /var/www/html/config        
      - type: volume
        source: nextcloud_data
        target: /var/www/html/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}  
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=$NEXTCLOUD_POSTGRES_PASSWORD
      - POSTGRES_DB=$NEXTCLOUD_POSTGRES_DATABASE
      - POSTGRES_USER=$NEXTCLOUD_POSTGRES_USER  
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=192.168.40.254
      - SMTP_HOST=smtp.mailbox.org
      - SMTP_SECURE=tls
      - SMTP_PORT=587
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=$SMTP_NAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - NEXTCLOUD_MAIL_FROM_ADDRESS=info@nextcloud.dir.li
    # env_file:
    #   - db.env
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      ##################### CALDAV

      ##################### HTTPS
      ########################### Entrypoint
      - "traefik.http.routers.nextcloud-https.entrypoints=https"
      ########################### Rules
      - "traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.$DOMAINNAME`, `nextcloud2.$DOMAINNAME`)"
      ########################### TLS Settings
      - "traefik.http.routers.nextcloud-https.tls=true"
      - "traefik.http.routers.nextcloud-https.tls.certresolver=dns-cloudflare"
      ########################### Middleware
      - "traefik.http.routers.nextcloud-https.middlewares=nextcloud-caldav@docker"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-https.middlewares=chain-no-auth@file" # No Authentication
      ########################### Service
      - "traefik.http.routers.nextcloud-https.service=nextcloud-svc"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.scheme=http"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=80"

  cron:
    container_name: cron
    image: nextcloud:apache
    restart: always
    networks:
    - backend
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

