version: "3.7"

services:
  # All services / apps go below this line
  ouroboros:
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=7600
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
